openapi: 3.0.0
info:
  version: 1.0.1
  title: FSJ-HUB-API
  x-logo:
    url: 'https://www.saojoaofarmacias.com.br/assets/images/logo.png'
  description:
    $ref: ./info-description.md
tags:
  - name: Intencao compra
    description: Gerar intencao dos produtos.
  - name: Pré-Autorizacao
    description: Pre-autorizar os produtos que se encontram no carrinho do cliente para buscar os descontos atuais dos laboratórios.
  - name: Confirmar Pré-autorizacao
    description: Confirmar os produtos pré-autorizados no carrinho.
  - name: Autorizacao
    description: Encerrar o fluxo de venda confirmando ou cancelando a venda
servers:
  - url: 'https://example.com/api'
paths:
  /hubIntencaoCompra:
    $ref: paths/intencao_compra.yaml
  /hubPreAutorizar:
    $ref: paths/pre_autorizacao.yaml
  /hubConfirmaPreAutorizar:
    $ref: paths/confirma_pre_autorizacao.yaml
  /hubAutorizar:
    $ref: paths/autorizacao_post.yaml
  /hubAutorizar/{id}:
    $ref: paths/autorizacao_delete.yaml
